create table if not exists public.execution_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null,
  mode text not null,
  symbol text,
  side text,
  status text not null,
  order_id text,
  message text not null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists execution_audit_created_at_idx on public.execution_audit (created_at desc);
create index if not exists execution_audit_order_id_idx on public.execution_audit (order_id);

alter table public.execution_audit enable row level security;

revoke all on public.execution_audit from anon, authenticated;

-- The server writes through SUPABASE_SERVICE_ROLE_KEY. No client role may read or write audit records.
