'use client';
import{useCallback,useEffect,useMemo,useRef,useState}from'react';
import IntelMap from'./IntelMap';
import{Tool,LayerPanel,IntelPanel,EngineHud,Ticker,EventCard}from'./HudPanels';
import{Drawer,Loading,DossierContent,BriefingContent,RegionContent,HelpModal}from'./Drawers';
import{START,TARGET,haversine}from'../lib/format.js';
import SimpleDashboard from './SimpleDashboard';
const DEFAULT_LAYERS={geopolitical:true,hazard:true,seismic:true,news:false};
export default function CommandCenter({token,user,onLock}){const[engine,setEngine]=useState(null),[intel,setIntel]=useState(null),[briefing,setBriefing]=useState(null),[dossier,setDossier]=useState(null),[region,setRegion]=useState(null),[layers,setLayers]=useState(DEFAULT_LAYERS),[layerPanel,setLayerPanel]=useState(true),[intelPanel,setIntelPanel]=useState(true),[marketsPanel,setMarketsPanel]=useState(true),[briefingOpen,setBriefingOpen]=useState(false),[dossierOpen,setDossierOpen]=useState(false),[regionOpen,setRegionOpen]=useState(false),[helpOpen,setHelpOpen]=useState(false),[selectedEventId,setSelectedEventId]=useState(''),[search,setSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(''),[connected,setConnected]=useState(false);const searchRef=useRef(null),headers=useCallback(extra=>({...extra,...(token?{'x-ce-token':token}:{})}),[token]),api=useCallback(async(path,options={})=>{const r=await fetch(path,{...options,headers:headers(options.headers||{}),cache:'no-store'}),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`Request failed (${r.status})`);return b},[headers]);
const refresh=useCallback(async()=>{setBusy('refresh');try{const[e,i]=await Promise.all([api('/api/engine'),api('/api/intel')]);setEngine(e);setIntel(i);setConnected(true);setError('')}catch(e){setConnected(false);setError(String(e.message||e))}finally{setBusy('')}},[api]);
const action=useCallback(async a=>{setBusy(a);try{setEngine(await api('/api/engine',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:a})}));setConnected(true);setError('')}catch(e){setError(String(e.message||e))}finally{setBusy('')}},[api]);
const loadDossier=useCallback(async symbol=>{const s=String(symbol||'').toUpperCase().replace(/[^A-Z.-]/g,'').slice(0,10);if(!s)return;setBusy('dossier');setDossierOpen(true);setSearch(s);try{setDossier(await api(`/api/dossier?symbol=${encodeURIComponent(s)}`));setError('')}catch(e){setDossier(null);setError(String(e.message||e))}finally{setBusy('')}},[api]);
const loadBriefing=useCallback(async()=>{setBusy('briefing');setBriefingOpen(true);try{setBriefing(await api('/api/briefing',{method:'POST'}));setError('')}catch(e){setBriefing(null);setError(String(e.message||e))}finally{setBusy('')}},[api]);
useEffect(()=>{refresh();const a=setInterval(()=>api('/api/engine').then(setEngine).catch(()=>setConnected(false)),30000),b=setInterval(()=>api('/api/intel').then(d=>{setIntel(d);setConnected(true)}).catch(()=>setConnected(false)),60000);return()=>{clearInterval(a);clearInterval(b)}},[api,refresh]);
useEffect(()=>{const key=e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){if(e.key==='Escape')document.activeElement.blur();return}if(e.key==='?')setHelpOpen(v=>!v);else if(e.key.toLowerCase()==='l')setLayerPanel(v=>!v);else if(e.key.toLowerCase()==='i')setIntelPanel(v=>!v);else if(e.key.toLowerCase()==='m')setMarketsPanel(v=>!v);else if(e.key.toLowerCase()==='b')loadBriefing();else if(e.key.toLowerCase()==='r')window.dispatchEvent(new Event('causaledge-reset-map'));else if(e.key==='/'||(e.metaKey&&e.key.toLowerCase()==='k')){e.preventDefault();searchRef.current?.focus()}else if(e.key==='Escape'){setHelpOpen(false);setBriefingOpen(false);setDossierOpen(false);setRegionOpen(false)}else if(e.key.toLowerCase()==='f'){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[loadBriefing]);
const filtered=useMemo(()=>(intel?.events||[]).filter(e=>layers[e.type]!==false),[intel,layers]),priority=useMemo(()=>filtered.slice().sort((a,b)=>(b.severity-a.severity)||(Date.parse(b.timestamp||0)-Date.parse(a.timestamp||0))).slice(0,28),[filtered]),selected=useMemo(()=>(intel?.events||[]).find(e=>e.id===selectedEventId)||null,[intel,selectedEventId]),markets=intel?.markets||[],alerts=useMemo(()=>[...(intel?.events||[]).filter(e=>Number(e.severity)>=4),...markets.filter(m=>Math.abs(Number(m.changePct))>=3)].length,[intel,markets]),nearby=useMemo(()=>!region?[]:(intel?.events||[]).filter(e=>Number.isFinite(Number(e.lat))&&Number.isFinite(Number(e.lon))).map(e=>({...e,distance:haversine(region,{lat:Number(e.lat),lon:Number(e.lon)})})).filter(e=>e.distance<=1500).sort((a,b)=>a.distance-b.distance).slice(0,14),[intel,region]);
const account=engine?.account||{},start=Number(engine?.challenge?.start||START),target=Number(engine?.challenge?.target||TARGET),equity=Number(account.equity||start),progress=Math.max(0,Math.min(100,((equity-start)/Math.max(target-start,1))*100)),returnPct=start?((equity-start)/start)*100:0,sourceOk=(intel?.sourceStatus||[]).filter(s=>s.ok).length,sourceTotal=(intel?.sourceStatus||[]).length;
function submit(e){e.preventDefault();loadDossier(search)}function pickEvent(e){setSelectedEventId(e.id);if(e.symbols?.[0])setSearch(e.symbols[0])}const regionPick=useCallback(p=>{setRegion(p);setRegionOpen(true);setDossierOpen(false);setBriefingOpen(false)},[])
return <SimpleDashboard engine={engine} intel={intel} busy={busy} onAction={action} onBrief={loadBriefing} onDossier={loadDossier} onLock={onLock}/> }
