'use client';
import{money,pct,shortTime,typeLabel}from'../lib/format.js';
export function Drawer({title,onClose,children,wide}){return <aside className={`drawer ${wide?'wide':''}`}><div className="drawerHead"><b>{title}</b><button onClick={onClose}>×</button></div><div className="drawerBody">{children}</div></aside>}
export function Loading({text}){return <div className="loadingState"><span className="radarSpinner"/><b>{text}</b></div>}
function Metric({label,value}){return <div><span>{label}</span><b>{value}</b></div>}
function Graph({graph,onNode}){const nodes=graph?.nodes||[];if(!nodes.length)return <div className="emptyState">No relationship graph available.</div>;const root=nodes[0],outer=nodes.slice(1,9),cx=180,cy=140,r=96,points=outer.map((n,i)=>({...n,x:cx+Math.cos((i/Math.max(outer.length,1))*Math.PI*2-Math.PI/2)*r,y:cy+Math.sin((i/Math.max(outer.length,1))*Math.PI*2-Math.PI/2)*r}));return <div className="graphWrap"><svg viewBox="0 0 360 280" role="img" aria-label={`${root.label} relationship graph`}>{points.map(n=><line key={`l-${n.id}`} x1={cx} y1={cy} x2={n.x} y2={n.y}/>)}<g className="graphRoot" onClick={()=>onNode(root.id)}><circle cx={cx} cy={cy} r="31"/><text x={cx} y={cy+4}>{root.label}</text></g>{points.map(n=><g className="graphNode" key={n.id} onClick={()=>onNode(n.id)}><circle cx={n.x} cy={n.y} r="23"/><text x={n.x} y={n.y+4}>{n.label}</text></g>)}</svg></div>}
export function DossierContent({data,onSymbol}){const m=data.market||{},ai=data.ai||{};return <><section className="dossierHero"><div><span className="eyebrow">{data.exchange||'US EQUITY'} · {data.fractionable?'FRACTIONAL':'WHOLE SHARE'}</span><h2>{data.name}</h2><p>{data.symbol}</p></div><div className="priceBlock"><b>{money(m.price)}</b><span className={Number(m.changePct)>=0?'positive':'negative'}>{pct(m.changePct)}</span></div></section><div className="dossierMetrics"><Metric label="DAY HIGH" value={money(m.high)}/><Metric label="DAY LOW" value={money(m.low)}/><Metric label="VOLUME" value={Number(m.volume||0).toLocaleString()}/><Metric label="AI CONF." value={`${Number(ai.confidence||0).toFixed(0)}%`}/></div><section className="intelBlock"><span className={`stance ${String(ai.stance||'').toLowerCase()}`}>{ai.stance||'Neutral'}</span><h3>{ai.catalyst}</h3><p>{ai.thesis}</p><small>Horizon: {ai.horizon}</small></section>{ai.risks?.length?<section><div className="sectionLabel">KEY RISKS</div><ul className="riskBullets">{ai.risks.map((r,i)=><li key={i}>{r}</li>)}</ul></section>:null}<section><div className="sectionLabel">ENTITY RELATIONSHIPS</div><Graph graph={data.graph} onNode={onSymbol}/></section><section><div className="sectionLabel">RECENT NEWS</div><div className="dossierNews">{data.news?.slice(0,10).map(n=><article key={n.id}><div><span>{n.source}</span><time>{shortTime(n.timestamp)}</time></div><b>{n.title}</b><p>{n.summary}</p></article>)}</div></section></>}
export function BriefingContent({data,onSymbol}){return <><div className={`briefPriority ${String(data.priority||'').toLowerCase()}`}>{data.priority} PRIORITY</div><h2 className="briefHeadline">{data.headline}</h2><p className="drawerLead">{data.summary}</p><div className="briefItems">{data.items?.map((item,i)=><article key={i}><div><span>{String(i+1).padStart(2,'0')}</span><b>{item.title}</b><i>{Number(item.confidence||0).toFixed(0)}%</i></div><p>{item.why}</p>{item.relatedSymbols?.length?<div className="symbolLinks">{item.relatedSymbols.map(s=><button key={s} onClick={()=>onSymbol(s)}>{s}</button>)}</div>:null}</article>)}</div><small className="aiDisclosure">AI correlation layer · generated from the currently normalized event and market feeds.</small></>}
export function RegionContent({region,nearby,onEvent}){return <><div className="regionCoords">{region?.lat?.toFixed(3)}, {region?.lon?.toFixed(3)} <span>RIGHT-CLICK CONTEXT</span></div><p className="drawerLead">Composite view of intelligence events within 1,500 km of the selected location.</p><div className="regionFeed">{nearby.length?nearby.map(e=><button key={e.id} onClick={()=>onEvent(e)}><span className={`typeTag ${e.type}`}>{typeLabel(e.type)}</span><b>{e.title}</b><small>{Math.round(e.distance)} km · {e.source}</small></button>):<div className="emptyState">No current normalized events near this point.</div>}</div></>}
export function HelpModal({onClose}){const rows=[['L','Toggle layers'],['I','Toggle intelligence feed'],['M','Toggle markets ticker'],['B','Generate AI briefing'],['R','Reset global map'],['F','Fullscreen'],['/','Focus ticker search'],['ESC','Close active panels']];return <div className="modalBackdrop" onClick={onClose}><section className="helpModal" onClick={e=>e.stopPropagation()}><button className="closeX" onClick={onClose}>×</button><p className="eyebrow">KEYBOARD COMMANDS</p><h2>SignalForge shortcuts</h2>{rows.map(([k,t])=><div className="shortcut" key={k}><kbd>{k}</kbd><span>{t}</span></div>)}</section></div>}
