'use client';
import{money,pct,shortTime,typeLabel}from'../lib/format.js';
export function Tool({active,label,glyph,onClick,badge}){return <button className={`toolButton ${active?'active':''}`} onClick={onClick}><span>{glyph}</span><small>{label}</small>{badge?<i>{badge>9?'9+':badge}</i>:null}</button>}
export function PanelTitle({title,sub,onClose}){return <div className="panelTitle"><div><b>{title}</b><small>{sub}</small></div><button onClick={onClose}>×</button></div>}
function Layer({keyName,label,note,checked,setLayers,dot}){return <label className="layerRow"><input type="checkbox" checked={Boolean(checked)} onChange={e=>setLayers(l=>({...l,[keyName]:e.target.checked}))}/><span className={`layerDot ${dot}`}/><span><b>{label}</b><small>{note}</small></span><i>{checked?'ON':'OFF'}</i></label>}
export function LayerPanel({intel,layers,setLayers,equity,progress,target,returnPct,onClose}){return <aside className="hudPanel layerHud"><PanelTitle title="INTELLIGENCE LAYERS" sub="Build your operating picture" onClose={onClose}/><div className="challengeMini"><div className="miniTop"><span>$100 CHALLENGE</span><b>{money(equity)}</b></div><div className="miniProgress"><i style={{width:`${progress}%`}}/></div><div className="miniMeta"><span className={returnPct>=0?'positive':'negative'}>{pct(returnPct)}</span><span>{progress.toFixed(1)}% to {money(target)}</span></div></div><div className="layerList"><Layer keyName="geopolitical" label="Geopolitical events" note="OSIRIS / GDELT" checked={layers.geopolitical} setLayers={setLayers} dot="geo"/><Layer keyName="hazard" label="Natural hazards" note="OSIRIS / NASA EONET" checked={layers.hazard} setLayers={setLayers} dot="haz"/><Layer keyName="seismic" label="Seismic activity" note="OSIRIS / USGS" checked={layers.seismic} setLayers={setLayers} dot="sei"/><Layer keyName="news" label="Market news markers" note="Alpaca News" checked={layers.news} setLayers={setLayers} dot="nws"/></div><div className="sectionLabel">SYSTEM SOURCES</div><div className="sourceList">{(intel?.sourceStatus||[]).map(s=><div className="sourceRow" key={s.name} title={s.error}><span className={`signalDot ${s.ok?'on':'off'}`}/><span>{s.name}</span><b>{s.ok?'UP':'DOWN'}</b></div>)}</div></aside>}
export function IntelPanel({events,alerts,onClose,onSelect,setLayers}){return <aside className="hudPanel intelHud"><PanelTitle title="LIVE INTELLIGENCE" sub={`${events.length} priority items · ${alerts} alerts`} onClose={onClose}/><div className="intelTabs"><button className="active">ALL</button><button onClick={()=>setLayers(l=>({...l,news:!l.news}))}>NEWS</button><button onClick={()=>setLayers(l=>({...l,geopolitical:!l.geopolitical}))}>GEO</button></div><div className="intelFeed">{events.map(e=><button className={`intelItem sev${e.severity}`} key={e.id} onClick={()=>onSelect(e)}><div><span className={`typeTag ${e.type}`}>{typeLabel(e.type)}</span><time>{shortTime(e.timestamp)}</time></div><b>{e.title}</b><p>{e.summary||e.country||e.source}</p><footer><span>{e.source}</span>{e.symbols?.length?<span>{e.symbols.slice(0,4).join(' · ')}</span>:null}</footer></button>)}</div></aside>}
export function EngineHud({engine,busy,onAction}){const a=engine?.account||{},positions=engine?.positions||[];return <section className="engineHud"><div className="engineState"><span className={`pulse ${engine?.engine?.paused?'paused':engine?.engine?.enabled?'on':''}`}/><div><small>AUTONOMOUS ENGINE</small><b>{engine?.engine?.paused?'PAUSED':engine?.engine?.enabled?'MONITORING':'OFF'}</b></div></div><div className="engineMetrics"><span><small>DAY</small><b className={Number(a.dayPnl)>=0?'positive':'negative'}>{money(a.dayPnl)}</b></span><span><small>POSITIONS</small><b>{positions.length}/{engine?.challenge?.maxPositions??2}</b></span><span><small>DAILY STOP</small><b>{money(engine?.challenge?.dailyLossLimit)}</b></span></div><div className="engineActions"><button className="runBtn" disabled={Boolean(busy)||!engine?.safety?.paperExecution} onClick={()=>onAction('run')}>{busy==='run'?'RUNNING…':'RUN CYCLE'}</button><button disabled={Boolean(busy)} onClick={()=>onAction(engine?.engine?.paused?'resume':'pause')}>{engine?.engine?.paused?'RESUME':'PAUSE'}</button><button className="dangerText" disabled={Boolean(busy)||!positions.length} onClick={()=>onAction('close-all')}>CLOSE ALL</button></div></section>}
export function Ticker({markets,onSymbol}){return <div className="tickerDock"><div className="tickerLabel"><span className="signalDot on"/><b>MARKETS</b></div><div className="tickerTrack">{markets.map(m=><button className="tickerItem" key={m.symbol} onClick={()=>onSymbol(m.symbol)}><b>{m.symbol}</b><span>{money(m.price)}</span><i className={Number(m.changePct)>=0?'positive':'negative'}>{pct(m.changePct)}</i></button>)}</div></div>}
export function EventCard({event,onClose,onSymbol}){if(!event)return null;return <section className="eventCard"><button className="closeX" onClick={onClose}>×</button><span className={`typeTag ${event.type}`}>{typeLabel(event.type)} · SEV {event.severity}</span><h3>{event.title}</h3><p>{event.summary}</p><div className="eventMeta"><span>{event.source}</span><span>{event.country}</span><span>{shortTime(event.timestamp)}</span></div>{event.symbols?.length?<div className="symbolLinks">{event.symbols.map(s=><button key={s} onClick={()=>onSymbol(s)}>{s} DOSSIER</button>)}</div>:null}</section>}
