export const DATA_BASE='https://data.alpaca.markets';
export const PAPER_BASE='https://paper-api.alpaca.markets';
export const OSIRIS_BASE='https://www.osirisai.live/api';
export const WATCHLIST=(process.env.CHALLENGE_WATCHLIST||'AAPL,MSFT,NVDA,AMZN,META,GOOGL,TSLA,AMD,JPM,SPY,LMT,XOM,CVX,BA,RTX').split(',').map(s=>s.trim().toUpperCase()).filter(Boolean).slice(0,30);
export function alpacaHeaders(){return{'APCA-API-KEY-ID':process.env.ALPACA_API_KEY||'','APCA-API-SECRET-KEY':process.env.ALPACA_API_SECRET||'','Content-Type':'application/json'};}
export async function fetchJson(url,options={},timeoutMs=9000){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(url,{...options,signal:c.signal,cache:'no-store'});const x=await r.text();let d=null;try{d=x?JSON.parse(x):null}catch{}if(!r.ok)throw new Error(d?.error||d?.message||`${r.status} ${r.statusText}`);return d}finally{clearTimeout(t)}}
export function arr(v){if(Array.isArray(v))return v;if(!v||typeof v!=='object')return[];for(const k of['events','items','data','features','results','incidents','countries','risks','suppliers','news','earthquakes','alerts','hotspots','weather'])if(Array.isArray(v[k]))return v[k];const e=Object.entries(v).filter(([,x])=>x&&typeof x==='object'&&!Array.isArray(x));return e.length&&e.length<=300?e.map(([k,x])=>({name:x.name||k,country:x.country||k,...x})):[]}
function coords(i={}){const g=i.geometry||i.geo||i.location||{},c=g.coordinates||i.coordinates;if(Array.isArray(c)&&c.length>=2&&Number.isFinite(Number(c[0]))&&Number.isFinite(Number(c[1])))return{lon:Number(c[0]),lat:Number(c[1])};const lat=Number(i.lat??i.latitude??g.lat??g.latitude),lon=Number(i.lon??i.lng??i.longitude??g.lon??g.lng??g.longitude);return Number.isFinite(lat)&&Number.isFinite(lon)?{lat,lon}:{lat:null,lon:null}}
function severity(i={},fallback=1){const p=i.properties||{},raw=Number(i.severity??i.risk_score??i.riskScore??i.score??i.magnitude??i.mag??p.mag??p.magnitude??p.severity);if(Number.isFinite(raw)){if(raw<=5)return Math.max(1,Math.min(5,Math.round(raw)));if(raw<=10)return Math.max(1,Math.min(5,Math.round(raw/2)));return Math.max(1,Math.min(5,Math.round(raw/20)))}const x=String(i.severity||i.level||i.priority||'').toLowerCase();if(/critical|extreme|red/.test(x))return 5;if(/high|severe|orange/.test(x))return 4;if(/medium|moderate|yellow/.test(x))return 3;if(/low|minor|green/.test(x))return 2;return fallback}
export function normalizeEvent(i,type,source,index=0){const{lat,lon}=coords(i),p=i.properties||{},title=i.title||i.name||i.headline||i.event||p.title||p.name||`${type} event`,summary=i.summary||i.description||i.detail||p.description||p.place||'',ts=i.timestamp||i.created_at||i.updated_at||i.date||p.time||p.updated||null,symbols=i.symbols||i.tickers||i.related_symbols||[];return{id:String(i.id||i.event_id||i.url||`${source}-${type}-${index}-${title}`).slice(0,180),type,source,title:String(title).slice(0,240),summary:String(summary).slice(0,700),timestamp:typeof ts==='number'?new Date(ts).toISOString():ts,lat,lon,severity:severity(i,type==='news'?2:3),symbols:Array.isArray(symbols)?symbols.map(s=>String(s).toUpperCase()).slice(0,8):[],country:i.country||i.country_code||p.country||'',url:i.url||i.link||p.url||''}}
export function normalizeLoose(data,type,source,limit=120){return arr(data).slice(0,limit).map((i,n)=>normalizeEvent(i,type,source,n))}
export function flattenRisk(data){return arr(data).slice(0,80).map(i=>({country:i.country||i.name||i.country_name||i.iso3||i.code||'Unknown',code:i.code||i.iso2||i.iso3||'',risk:Number(i.risk_score??i.risk??i.score??0),level:i.level||i.risk_level||i.status||'',marketSession:i.market_session||i.marketSession||''}))}
export function flattenSuppliers(data){return arr(data).slice(0,80).map(i=>({name:i.name||i.company||i.supplier||'Supplier',symbol:String(i.symbol||i.ticker||'').toUpperCase(),country:i.country||i.location||'',criticality:i.criticality||i.risk||i.level||'',sector:i.sector||i.industry||''}))}
