import{DATA_BASE,PAPER_BASE,OSIRIS_BASE,WATCHLIST,alpacaHeaders,fetchJson,normalizeEvent,normalizeLoose,flattenRisk,flattenSuppliers}from'./core.js';
async function osiris(path){return fetchJson(`${OSIRIS_BASE}${path}`,{headers:{'User-Agent':'CausalEdge-Markets/1.0 intelligence dashboard'}},8000)}
async function directEarthquakes(){const d=await fetchJson('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson',{},8000);return(d?.features||[]).slice(0,120).map((f,i)=>normalizeEvent({...f.properties,id:f.id,geometry:f.geometry,magnitude:f.properties?.mag},'seismic','USGS',i))}
async function directEonet(){const d=await fetchJson('https://eonet.gsfc.nasa.gov/api/v3/events?status=open&limit=100',{},8000);return(d?.events||[]).map((e,i)=>normalizeEvent({...e,geometry:Array.isArray(e.geometry)?e.geometry.at(-1):null,severity:3},'hazard','NASA EONET',i))}
export async function fetchAlpacaNews(symbols=WATCHLIST,limit=30){if(!process.env.ALPACA_API_KEY||!process.env.ALPACA_API_SECRET)return[];const d=await fetchJson(`${DATA_BASE}/v1beta1/news?sort=desc&limit=${limit}&include_content=false&symbols=${encodeURIComponent(symbols.join(','))}`,{headers:alpacaHeaders()},8000);return(d?.news||[]).map((n,i)=>normalizeEvent(n,'news',n.source||'Alpaca News',i))}
export async function fetchMarketSnapshots(symbols=WATCHLIST){if(!process.env.ALPACA_API_KEY||!process.env.ALPACA_API_SECRET)return[];const d=await fetchJson(`${DATA_BASE}/v2/stocks/snapshots?symbols=${encodeURIComponent(symbols.join(','))}&feed=iex`,{headers:alpacaHeaders()},8000),s=d?.snapshots||d||{};return symbols.map(symbol=>{const x=s[symbol]||{},price=Number(x.latestTrade?.p||x.minuteBar?.c||x.dailyBar?.c||0),prev=Number(x.prevDailyBar?.c||0);return{symbol,price,changePct:prev>0&&price>0?((price-prev)/prev)*100:0,volume:Number(x.dailyBar?.v||0),open:Number(x.dailyBar?.o||0),high:Number(x.dailyBar?.h||0),low:Number(x.dailyBar?.l||0),bid:Number(x.latestQuote?.bp||0),ask:Number(x.latestQuote?.ap||0),timestamp:x.latestTrade?.t||x.minuteBar?.t||null}}).filter(q=>q.price>0)}
async function fetchClock(){if(!process.env.ALPACA_API_KEY||!process.env.ALPACA_API_SECRET)return null;try{const c=await fetchJson(`${PAPER_BASE}/v2/clock`,{headers:alpacaHeaders()},5000);return{isOpen:Boolean(c.is_open),nextOpen:c.next_open,nextClose:c.next_close,timestamp:c.timestamp}}catch{return null}}
export async function buildIntelSnapshot(){const r=await Promise.allSettled([osiris('/gdelt'),osiris('/country-risk'),osiris('/scm-suppliers'),osiris('/earthquakes'),osiris('/weather'),fetchAlpacaNews(),fetchMarketSnapshots(),fetchClock()]),[gdelt,risk,suppliers,quakes,weather,news,markets,clock]=r,status=[['OSIRIS / GDELT',gdelt],['OSIRIS / Country Risk',risk],['OSIRIS / Supply Chain',suppliers],['OSIRIS / Seismic',quakes],['OSIRIS / Weather',weather],['Alpaca News',news],['Alpaca Markets',markets],['Alpaca Clock',clock]].map(([name,x])=>({name,ok:x.status==='fulfilled',error:x.status==='rejected'?String(x.reason?.message||x.reason).slice(0,160):''}));let seismic=quakes.status==='fulfilled'?normalizeLoose(quakes.value,'seismic','OSIRIS'):[],hazards=weather.status==='fulfilled'?normalizeLoose(weather.value,'hazard','OSIRIS'):[];if(!seismic.length)try{seismic=await directEarthquakes();status.push({name:'USGS fallback',ok:true,error:''})}catch(e){status.push({name:'USGS fallback',ok:false,error:String(e?.message||e)})}if(!hazards.length)try{hazards=await directEonet();status.push({name:'NASA EONET fallback',ok:true,error:''})}catch(e){status.push({name:'NASA EONET fallback',ok:false,error:String(e?.message||e)})}const geo=gdelt.status==='fulfilled'?normalizeLoose(gdelt.value,'geopolitical','OSIRIS / GDELT'):[],n=news.status==='fulfilled'?news.value:[],events=[...geo,...hazards,...seismic,...n].sort((a,b)=>(b.severity-a.severity)||(Date.parse(b.timestamp||0)-Date.parse(a.timestamp||0))).slice(0,260);return{timestamp:new Date().toISOString(),watchlist:WATCHLIST,clock:clock.status==='fulfilled'?clock.value:null,markets:markets.status==='fulfilled'?markets.value:[],news:n.slice(0,40),events,countryRisk:risk.status==='fulfilled'?flattenRisk(risk.value):[],suppliers:suppliers.status==='fulfilled'?flattenSuppliers(suppliers.value):[],sourceStatus:status}}
export async function fetchMacroContext(){const[g,r]=await Promise.allSettled([osiris('/gdelt'),osiris('/country-risk')]);return{events:g.status==='fulfilled'?normalizeLoose(g.value,'geopolitical','OSIRIS / GDELT',15).map(e=>({title:e.title,severity:e.severity,country:e.country})):[],countryRisk:r.status==='fulfilled'?flattenRisk(r.value).sort((a,b)=>b.risk-a.risk).slice(0,12):[]}}
